# Generated by Django 5.2.5 on 2025-08-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Aircraft model')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('rows', models.PositiveIntegerField(verbose_name='Rows')),
                ('columns', models.PositiveIntegerField(verbose_name='Columns')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Aircraft',
                'verbose_name_plural': 'Aircraft',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True, verbose_name='Flight number')),
                ('origin', models.CharField(max_length=100, verbose_name='Origin')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination')),
                ('departure_date', models.DateTimeField(verbose_name='Departure date')),
                ('arrival_date', models.DateTimeField(verbose_name='Arrival date')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Flight duration')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('boarding', 'Boarding'), ('in_flight', 'In Flight'), ('landed', 'Landed'), ('cancelled', 'Cancelled'), ('delayed', 'Delayed')], default='scheduled', max_length=20, verbose_name='Status')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['-departure_date'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5, verbose_name='Seat number')),
                ('row', models.PositiveIntegerField(verbose_name='Row')),
                ('column', models.CharField(max_length=1, verbose_name='Column')),
                ('type', models.CharField(choices=[('first', 'First Class'), ('business', 'Business Class'), ('economy', 'Economy Class')], default='economy', max_length=20, verbose_name='Seat type')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20, verbose_name='Status')),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.aircraft', verbose_name='Aircraft')),
            ],
            options={
                'verbose_name': 'Seat',
                'verbose_name_plural': 'Seats',
                'ordering': ['row', 'column'],
                'unique_together': {('aircraft', 'seat_number')},
            },
        ),
    ]
