# Generated by Django 5.2.5 on 2025-08-14 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Airplane model')),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('rows', models.PositiveIntegerField(verbose_name='Rows')),
                ('columns', models.PositiveIntegerField(verbose_name='Columns')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Airplane',
                'verbose_name_plural': 'Airplane',
                'ordering': ['model'],
            },
        ),
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='flight',
            name='Airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='flights.airplane', verbose_name='Airplane'),
        ),
        migrations.AddField(
            model_name='seat',
            name='Airplane',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.airplane', verbose_name='Airplane'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('Airplane', 'seat_number')},
        ),
        migrations.RemoveField(
            model_name='seat',
            name='aircraft',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
    ]
