# Generated by Django 5.2.5 on 2025-08-14 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airplane_remove_flight_aircraft_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airplane',
            options={'ordering': ['model'], 'verbose_name': 'Airplane', 'verbose_name_plural': 'Airplanes'},
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='Airplane',
            new_name='airplane',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='Airplane',
            new_name='airplane',
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together={('airplane', 'seat_number')},
        ),
    ]
