# Generated by Django 5.2.5 on 2025-08-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_airplane_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Extra price'),
        ),
    ]
