# Generated by Django 5.2.5 on 2025-08-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_seat_extra_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Determina si el vuelo se muestra en la web', verbose_name='Active'),
        ),
    ]
