# Generated by Django 5.2.5 on 2025-08-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_flight_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
