# Generated by Django 5.2.5 on 2025-11-02 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0006_alter_flight_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='registration',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='flight',
            name='managed_by',
            field=models.ForeignKey(blank=True, help_text='User who manages this flight', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_flights', to=settings.AUTH_USER_MODEL, verbose_name='Managed by'),
        ),
    ]
