# Generated by Django 5.2.5 on 2025-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full name')),
                ('document_type', models.CharField(choices=[('dni', 'dni'), ('passport', 'Passport'), ('cedula', 'ID Card'), ('license', 'Driver License')], default='dni', max_length=20, verbose_name='Document type')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='Document number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('birth_date', models.DateField(verbose_name='Birth date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
