# Generated by Django 5.2.5 on 2025-08-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passenger',
            options={'ordering': ['name'], 'verbose_name': 'Passenger', 'verbose_name_plural': 'Passengers'},
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passenger', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='document_type',
            field=models.CharField(choices=[('dni', 'DNI'), ('passport', 'Passport'), ('cedula', 'ID Card'), ('license', 'Driver License')], default='dni', max_length=20, verbose_name='Document type'),
        ),
    ]
