# Generated by Django 5.2.5 on 2025-08-14 22:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_alter_passenger_options_passenger_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Updated at'),
        ),
    ]
