# Generated by Django 5.2.5 on 2025-08-13 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='Reservation code')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total price')),
                ('reservation_date', models.DateTimeField(auto_now_add=True, verbose_name='Reservation date')),
                ('expiration_date', models.DateTimeField(blank=True, verbose_name='Expiration date')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.flight', verbose_name='Flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='passengers.passenger', verbose_name='Passenger')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='flights.seat', verbose_name='Seat')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-reservation_date'],
                'unique_together': {('flight', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Barcode')),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='issued', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Issue date')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservations.reservation', verbose_name='Reservation')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-issue_date'],
            },
        ),
    ]
