# Generated by Django 5.2.5 on 2025-08-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Notes'),
        ),
    ]
