# Generated by Django 5.2.5 on 2025-11-02 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0007_airplane_registration_flight_managed_by'),
        ('passengers', '0003_passenger_created_at_passenger_updated_at'),
        ('reservations', '0003_reservation_payment_method_reservation_payment_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('flight', 'passenger')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_comments',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Comments'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='flights.seat', verbose_name='Seat'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('issued', 'Issued'), ('used', 'Used'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='issued', max_length=20, verbose_name='Status'),
        ),
    ]
